# -*- coding: utf-8 -*-
"""simple linear regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ESIXO9rnnXmDgqZKq40sCOXdqrsya55z

#simple linear regresion
- This is an ml algorithm that is used to train the model.
- There will be one independent column and 1dependent column.
- We should consider the independent column as X and dependent column as y.
- Just assign the columns to the x and y variables.
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

#here age column and salary column are there in our data .
df=pd.read_csv('/content/simplelinearregression.csv')
df

#age is independent column and salary is dependent column
X=df[['Age']]
X.ndim #independent column should be in 2d array
y=df['Premium']
print(X)
print('--------------------------------------')
print(y)

"""- Once data is sepearated in dependend and independed then we should split the data according to our test and training size by giving that to the train test split function.
- We should import the module form the model selection that is in the sklearn.
"""

import sklearn
from sklearn.model_selection import train_test_split

"""- When we give the data to the train test split then it will give us four outputs.
- X_train,X_test,y_train,y_test this are thee values that need to be stored in the varialbes

- We give the variables that are created at the starting X and y.
"""

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42)
#we use test size for the data seperation for training and testing of the data.
# test size should be blw 0 and 1 for the correct seperation ,if we use integer values then that no. of values will be goes to the testing .

#now we should create the testing and training data sheets seperately.
#training data excel.
training_data=pd.DataFrame({'X_train':np.ravel(X_train),'y_train':y_train})
training_data

"""- When we give the X values that are in the 2d array but we should give that to the numpy and make that to 1d arary .
- y values are already in 1d so need to change that.
"""

#testing data excel
Testing_data=pd.DataFrame({'X_test':np.ravel(X_test),'y_test':y_test})
Testing_data

#training and testing data
print(len(X_train),len(y_train))#training
print(len(X_test),len(y_test)) #testing

"""- Now we train our data
- In simple linear regresion we train the data using the maths that is a straight line equation from that the data is trained and becomes the model.
- For training the data we give the data to the linear regression class in that there will be fit and predict fn that are used to train and test.

"""

from sklearn.linear_model import LinearRegression
reg=LinearRegression() #here we give our alogirthm to the object

reg.fit(X_train,y_train) #our algorithm is trained and the model is ready .

"""- y=m*+c is the algorithm that is trained and become a model.
- here we get the m-value and the c-value.
- m is the coeffecient and c is the intercept.
"""

m=reg.coef_
m

c=reg.intercept_
c

"""- If we get the m and c value then we can say that our data is properly trained and our algorithm has become a model.
- y=905.66*x-2405.66 -> model
"""

#now store the predicted ans in the variable using the predtic()fn
predict_ans=reg.predict(X_train)
predict_ans

training_data['predict_ans']=predict_ans
training_data

"""- When the model gives the prediction then we have the two questions.
- 1. does the answers given by the model are crct or not means checking the accuracy
- 2. where should the model need to improve means loss.

- **Accuracy**- to get the accuraacy we compare the y_train values and the y_cap values means the predict values.
- **Loss**- loss is the diff blw the actual point and the predicted point.
- To find the accuracy we find the r2_score in the regression.
- To find the loss we find the root mean squared error
- We can implement this using the built in fn and can also perform this manually using the formula and loops.
- r2_score= 1-(y-y^)**2/(y-ybar)**2
- root mean squared error=

#train performance
"""

training_data

# Accuracy without buit ins
n=0
d=0
for i in training_data.index:
  n=n+((training_data['y_train'][i]-training_data['predict_ans'][i])**2)
  d=d+((training_data['y_train'][i]-training_data['y_train'].mean())**2)

print(1-(n/d))

#loss without buitin
n=0
for i in training_data.index:
  n=n+((training_data['y_train'][i]-training_data['predict_ans'][i])**2)
print(n/len(training_data)-1)

import math
math.sqrt(398744543.15103054)

#loss
import sklearn
from sklearn.metrics import r2_score
from sklearn.metrics import root_mean_squared_error
from sklearn.metrics import mean_squared_error

print((r2_score(y_train,predict_ans))*100) #accuracy

print(mean_squared_error(y_train,predict_ans)/10000) #loss

"""**figure plot**"""

plt.figure(figsize=(5,3))
plt.title('Training data pattern')
plt.xlabel('Age column')
plt.ylabel('Premium')
plt.scatter(x = X_train,y = y_train,color='red',marker='*')
plt.plot(X_train,predict_ans,marker='s')
plt.show()

"""#test performance"""

test_predict_ans=reg.predict(X_test)
test_predict_ans

Testing_data['test_predict_ans']=test_predict_ans
Testing_data

print(r2_score(y_test,test_predict_ans)*100)

print(root_mean_squared_error(y_test,test_predict_ans)/100)

"""- Based on the training my model can give 84% accuracy and 27%loss.

#Testing with our own value

- For 29,49,24 age of people how much premium should be given
"""

print(round(reg.predict([[29]])[0],2))

print(round(reg.predict([[49]])[0],2))

print(round(reg.predict([[24]])[0],2))